services:
  air-backend:
    build: 
      context: .
    container_name: air-backend
    ports:
      - "5000:8080"

  keycloak:
    image: quay.io/keycloak/keycloak:26.5.6
    container_name: keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin 
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin 
    command: start-dev
    ports:
      - 8080:8080